# Compare pretrained weights
# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m_in21ft1k fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus=[0] es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m_in21ft1k fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=D gpus=[0] es_patience=6

# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m_in21k fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus=[0] es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m_in21k fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=D gpus=[0] es_patience=6

# # Pooled mask loss
# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=5 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=D gpus=[0] es_patience=6 loss_pooling=2
# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=5 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=D gpus=[0] es_patience=6 loss_pooling=4

# # Segmentation loss changed
# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=D gpus=[0] es_patience=6 lambda_lovasz=0.0 lambda_bce=0.5 lambda_focal=1.5 lambda_dice=0.0
# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=D gpus=[0] es_patience=6 lambda_lovasz=0.0 lambda_bce=0.5 lambda_focal=0.0 lambda_dice=1.5

# Compare tf_efficientnetv2_m_in21ft1k and tf_efficientnetv2_m in dice+bce setting
# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m_in21ft1k fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus=[1] es_patience=6 lambda_lovasz=0.0 lambda_bce=0.5 lambda_focal=0.0 lambda_dice=1.5
# python run.py lr=3e-4 logger=True project="siim-covid-model-test-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus=[1] es_patience=6 lambda_lovasz=0.0 lambda_bce=0.5 lambda_focal=0.0 lambda_dice=1.5

# 2 class
# python run.py lr=3e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt"
# python run.py lr=3e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=1 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf1-val_loss\=0.7143.ckpt"
# python run.py lr=3e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=2 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf2-val_loss\=0.7196.ckpt"
# python run.py lr=3e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=3 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf3-val_loss\=0.7625.ckpt"
# python run.py lr=3e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=4 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf4-val_loss\=0.7334.ckpt"

# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-test" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" epoch=1
# python run.py lr=1e-5 model=unet_smp_2c logger=True project="siim-covid-model-2c-test" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" epoch=1
# python run.py lr=1e-3 model=unet_smp_2c logger=True project="siim-covid-model-2c-test" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" epoch=1
# python run.py lr=1e-6 model=unet_smp_2c logger=True project="siim-covid-model-2c-test" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" epoch=1
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-test" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" epoch=1
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-test" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" epoch=1

# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=1 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=2 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=3 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=4 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls

# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls lr_schedule.name=null
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=1 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls lr_schedule.name=null
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=2 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls lr_schedule.name=null
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=3 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls lr_schedule.name=null
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=4 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=6 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.0 w_seg=0.0 losses=cls lr_schedule.name=null

# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.1 w_seg=0.0 losses=cls lr_schedule.name=null

# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" lr_schedule.name=null

# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf-640/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf0-val_loss\=0.7218.ckpt" w_enc=0.1 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=1 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf-640/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf1-val_loss\=0.7143.ckpt" w_enc=0.1 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=2 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf-640/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf2-val_loss\=0.7196.ckpt" w_enc=0.1 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=3 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf-640/tu_tf_efficientnetv2_m-640-aug-epoch\=09-sgkf3-val_loss\=0.7625.ckpt" w_enc=0.1 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=4 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-sgkf-640/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf4-val_loss\=0.7334.ckpt" w_enc=0.1 w_seg=0.0 losses=cls

# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-21ft1k-sgkf-640/tu_tf_efficientnetv2_m_in21ft1k-640-aug-epoch\=09-sgkf0-val_loss\=0.7246.ckpt" w_enc=0.1 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=1 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-21ft1k-sgkf-640/tu_tf_efficientnetv2_m_in21ft1k-640-aug-epoch\=09-sgkf1-val_loss\=0.7032.ckpt" w_enc=0.1 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=2 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-21ft1k-sgkf-640/tu_tf_efficientnetv2_m_in21ft1k-640-aug-epoch\=12-sgkf2-val_loss\=0.7200.ckpt" w_enc=0.1 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=3 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-21ft1k-sgkf-640/tu_tf_efficientnetv2_m_in21ft1k-640-aug-epoch\=13-sgkf3-val_loss\=0.7451.ckpt" w_enc=0.1 w_seg=0.0 losses=cls
# python run.py lr=1e-4 model=unet_smp_2c logger=True project="siim-covid-model-2c-cv" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=4 unet_smp.model_type=unetplusplus unet_smp.decoder_blocks=3 mask_type=both unet_smp.classes=2 cv=sgkf img_size=640 unet_smp.neck_type=F gpus="cuda:2" es_patience=10 smp_path="/root/siim-covid/output/efficientnet-v2-21ft1k-sgkf-640/tu_tf_efficientnetv2_m_in21ft1k-640-aug-epoch\=04-sgkf4-val_loss\=0.7439.ckpt" w_enc=0.1 w_seg=0.0 losses=cls

# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=0 unet_smp.decoder_blocks=3 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=1 unet_smp.decoder_blocks=3 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=2 unet_smp.decoder_blocks=3 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=3 unet_smp.decoder_blocks=3 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=4 unet_smp.decoder_blocks=3 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6

# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=0 unet_smp.decoder_blocks=5 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=1 unet_smp.decoder_blocks=5 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=2 unet_smp.decoder_blocks=5 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=3 unet_smp.decoder_blocks=5 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=4 unet_smp.decoder_blocks=5 cv=sgkf img_size=384 gpus="cuda:2" es_patience=6

# python run.py lr=1e-5 logger=True model=timm project="siim-covid-model-cv-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=0 cv=sgkf img_size=384 gpus="cuda:2" es_patience=10 alpha=0.5
# python run.py lr=1e-5 logger=True model=timm project="siim-covid-model-cv-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=1 cv=sgkf img_size=384 gpus="cuda:2" es_patience=10 alpha=0.5
# python run.py lr=1e-5 logger=True model=timm project="siim-covid-model-cv-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=2 cv=sgkf img_size=384 gpus="cuda:2" es_patience=10 alpha=0.5
# python run.py lr=1e-5 logger=True model=timm project="siim-covid-model-cv-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=3 cv=sgkf img_size=384 gpus="cuda:2" es_patience=10 alpha=0.5
# python run.py lr=1e-5 logger=True model=timm project="siim-covid-model-cv-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=4 cv=sgkf img_size=384 gpus="cuda:2" es_patience=10 alpha=0.5

# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-seg-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=0 cv=sgkf img_size=640 second_train=True epoch=16 gpus="cuda:2" es_patience=6 losses=seg
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-seg-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=1 cv=sgkf img_size=640 second_train=True epoch=16 gpus="cuda:2" es_patience=6 losses=seg
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-seg-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=2 cv=sgkf img_size=640 second_train=True epoch=16 gpus="cuda:2" es_patience=6 losses=seg
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-seg-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=3 cv=sgkf img_size=640 second_train=True epoch=16 gpus="cuda:2" es_patience=6 losses=seg
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-seg-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_m fold=4 cv=sgkf img_size=640 second_train=True epoch=16 gpus="cuda:2" es_patience=6 losses=seg

# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=0 gpus="cuda:2" es_patience=6 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=1 gpus="cuda:2" es_patience=6 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=2 gpus="cuda:2" es_patience=6 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=3 gpus="cuda:2" es_patience=6 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=4 gpus="cuda:2" es_patience=6 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"

# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=0 gpus="cuda:2" es_patience=6  w_enc=0.1 w_seg=0.1  load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=1 gpus="cuda:2" es_patience=6  w_enc=0.1 w_seg=0.1  load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=2 gpus="cuda:2" es_patience=6  w_enc=0.1 w_seg=0.1  load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=3 gpus="cuda:2" es_patience=6  w_enc=0.1 w_seg=0.1  load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=4 gpus="cuda:2" es_patience=6  w_enc=0.1 w_seg=0.1  load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=14-sgkf0-val_loss\=0.4892.ckpt"

# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=0 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=1 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=2 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=3 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=4 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"

# # Pretrained Unet on VinBigData
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-ft-gpu1" fold=0 gpus="cuda:2" es_patience=6 w_enc=1.0 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-ft-gpu1" fold=1 gpus="cuda:2" es_patience=6 w_enc=1.0 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-ft-gpu1" fold=2 gpus="cuda:2" es_patience=6 w_enc=1.0 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-ft-gpu1" fold=3 gpus="cuda:2" es_patience=6 w_enc=1.0 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-ft-gpu1" fold=4 gpus="cuda:2" es_patience=6 w_enc=1.0 w_seg=1.0 load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt"

# # RICORD Merged dataset and Pretrained Unet on VinBigData with no_ricord_val
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=0 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=0.1 dataset_postfix="-merge" load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt" no_ricord_val=true
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=1 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=0.1 dataset_postfix="-merge" load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt" no_ricord_val=true
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=2 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=0.1 dataset_postfix="-merge" load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt" no_ricord_val=true
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=3 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=0.1 dataset_postfix="-merge" load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt" no_ricord_val=true
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=4 gpus="cuda:2" es_patience=6 w_enc=0.1 w_seg=0.1 dataset_postfix="-merge" load_path="/shared/lorenzo/pl_output/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.4153.ckpt" no_ricord_val=true

# python run.py lr=3e-4 logger=True project="siim-covid-model-a-gpu1" fold=0 es_patience=6 batch_size=16 gpus="cuda:1"
# python run.py lr=3e-4 logger=True project="siim-covid-model-a-gpu1" fold=1 es_patience=6 batch_size=16 gpus="cuda:1"
# python run.py lr=3e-4 logger=True project="siim-covid-model-a-gpu1" fold=2 es_patience=6 batch_size=16 gpus="cuda:1"
# python run.py lr=3e-4 logger=True project="siim-covid-model-a-gpu1" fold=3 es_patience=6 batch_size=16 gpus="cuda:1"
# python run.py lr=3e-4 logger=True project="siim-covid-model-a-gpu1" fold=4 es_patience=6 batch_size=16 gpus="cuda:1"

# python run.py lr=3e-5 logger=True model=timm project="siim-covid-model-a-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=0 cv=sgkf img_size=384 gpus="cuda:1" es_patience=6 img_size=384 cv="sgkf" batch_size=32 model_config.pretrained_path="/home/lorenzo/siim-covid/pretrained/timm_nih-384-aug-epoch\=04-gkf0-val_loss\=0.1720.ckpt"
# python run.py lr=3e-5 logger=True model=timm project="siim-covid-model-a-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=1 cv=sgkf img_size=384 gpus="cuda:1" es_patience=6 img_size=384 cv="sgkf" batch_size=32 model_config.pretrained_path="/home/lorenzo/siim-covid/pretrained/timm_nih-384-aug-epoch\=04-gkf0-val_loss\=0.1720.ckpt"
# python run.py lr=3e-5 logger=True model=timm project="siim-covid-model-a-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=2 cv=sgkf img_size=384 gpus="cuda:1" es_patience=6 img_size=384 cv="sgkf" batch_size=32 model_config.pretrained_path="/home/lorenzo/siim-covid/pretrained/timm_nih-384-aug-epoch\=04-gkf0-val_loss\=0.1720.ckpt"
# python run.py lr=3e-5 logger=True model=timm project="siim-covid-model-a-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=3 cv=sgkf img_size=384 gpus="cuda:1" es_patience=6 img_size=384 cv="sgkf" batch_size=32 model_config.pretrained_path="/home/lorenzo/siim-covid/pretrained/timm_nih-384-aug-epoch\=04-gkf0-val_loss\=0.1720.ckpt"
# python run.py lr=3e-5 logger=True model=timm project="siim-covid-model-a-gpu1" model_config.backbone_name=swin_large_patch4_window12_384_in22k fold=4 cv=sgkf img_size=384 gpus="cuda:1" es_patience=6 img_size=384 cv="sgkf" batch_size=32 model_config.pretrained_path="/home/lorenzo/siim-covid/pretrained/timm_nih-384-aug-epoch\=04-gkf0-val_loss\=0.1720.ckpt"

# VinBigData pretrained
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-seg-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=0 cv=sgkf img_size=640 second_train=True epoch=6 gpus="cuda:1" es_patience=6 losses=seg dataset_postfix="-vin" batch_size=16

# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=0 gpus="cuda:1" es_patience=6 load_path="/home/lorenzo/siim-covid/pl_output/tu_tf_efficientnetv2_l-640-aug-epoch\=04-sgkf0-val_loss\=0.4182.ckpt" batch_size=12
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=1 gpus="cuda:1" es_patience=6 load_path="/home/lorenzo/siim-covid/pl_output/tu_tf_efficientnetv2_l-640-aug-epoch\=04-sgkf0-val_loss\=0.4182.ckpt" batch_size=12
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=2 gpus="cuda:1" es_patience=6 load_path="/home/lorenzo/siim-covid/pl_output/tu_tf_efficientnetv2_l-640-aug-epoch\=04-sgkf0-val_loss\=0.4182.ckpt" batch_size=12
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=3 gpus="cuda:1" es_patience=6 load_path="/home/lorenzo/siim-covid/pl_output/tu_tf_efficientnetv2_l-640-aug-epoch\=04-sgkf0-val_loss\=0.4182.ckpt" batch_size=12
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" unet_smp.backbone_name=tu-tf_efficientnetv2_l fold=4 gpus="cuda:1" es_patience=6 load_path="/home/lorenzo/siim-covid/pl_output/tu_tf_efficientnetv2_l-640-aug-epoch\=04-sgkf0-val_loss\=0.4182.ckpt" batch_size=12

# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=0 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/siim-covid/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=1 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/siim-covid/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=2 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/siim-covid/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=3 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/siim-covid/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"
# python run.py lr=3e-4 logger=True project="siim-covid-model-cv-gpu1" fold=4 gpus="cuda:1" es_patience=6 unet_smp.pretrain_path="/home/lorenzo/siim-covid/pretrained/unet_smp_nih-640-aug-epoch\=04-gkf0-val_loss\=0.0852.ckpt"

# python run.py lr=1e-4 model=unet_smp_2c logger=True project=siim-covid-model-2c-cv fold=0 img_size=640 gpus="cuda:0" epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/siim-covid/output/efficientnetv2_m_640_nih/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf0-val_loss\=0.7173.ckpt"
# python run.py lr=1e-4 model=unet_smp_2c logger=True project=siim-covid-model-2c-cv fold=1 img_size=640 gpus="cuda:0" epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/siim-covid/output/efficientnetv2_m_640_nih/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf1-val_loss\=0.6988.ckpt"
# python run.py lr=1e-4 model=unet_smp_2c logger=True project=siim-covid-model-2c-cv fold=2 img_size=640 gpus="cuda:0" epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/siim-covid/output/efficientnetv2_m_640_nih/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf2-val_loss\=0.7106.ckpt"
# python run.py lr=1e-4 model=unet_smp_2c logger=True project=siim-covid-model-2c-cv fold=3 img_size=640 gpus="cuda:0" epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/siim-covid/output/efficientnetv2_m_640_nih/tu_tf_efficientnetv2_m-640-aug-epoch\=04-sgkf3-val_loss\=0.7454.ckpt"
# python run.py lr=1e-4 model=unet_smp_2c logger=True project=siim-covid-model-2c-cv fold=4 img_size=640 gpus="cuda:0" epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/siim-covid/output/efficientnetv2_m_640_nih/tu_tf_efficientnetv2_m-640-aug-epoch\=08-sgkf4-val_loss\=0.7338.ckpt"

# python run.py lr=1e-5 model=timm_2c logger=True project=siim-covid-model-2c-cv fold=0 img_size=384 gpus="cuda:0" epoch=5 model_path="/home/lorenzo/siim-covid/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=05-sgkf0-val_loss\=0.8677.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
# python run.py lr=1e-5 model=timm_2c logger=True project=siim-covid-model-2c-cv fold=1 img_size=384 gpus="cuda:0" epoch=5 model_path="/home/lorenzo/siim-covid/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=06-sgkf1-val_loss\=0.8142.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
# python run.py lr=1e-5 model=timm_2c logger=True project=siim-covid-model-2c-cv fold=2 img_size=384 gpus="cuda:0" epoch=5 model_path="/home/lorenzo/siim-covid/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=04-sgkf2-val_loss\=0.8851.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
# python run.py lr=1e-5 model=timm_2c logger=True project=siim-covid-model-2c-cv fold=3 img_size=384 gpus="cuda:0" epoch=5 model_path="/home/lorenzo/siim-covid/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=07-sgkf3-val_loss\=0.8961.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
# python run.py lr=1e-5 model=timm_2c logger=True project=siim-covid-model-2c-cv fold=4 img_size=384 gpus="cuda:0" epoch=5 model_path="/home/lorenzo/siim-covid/output/swin_nihft_384/timm-swin_large_patch4_window12_384_in22k-384-aug-epoch\=04-sgkf4-val_loss\=0.8842.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"

python run.py lr=1e-4 model=unet_smp_2c logger=True project=siim-covid-model-2c-cv fold=0 img_size=512 gpus="cuda:0" epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/siim-covid/output/efficientnetv2-sgkf-512/tu_tf_efficientnetv2_m-512-aug-epoch04-sgkf0-val_loss0.7306.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-4 model=unet_smp_2c logger=True project=siim-covid-model-2c-cv fold=1 img_size=512 gpus="cuda:0" epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/siim-covid/output/efficientnetv2-sgkf-512/tu_tf_efficientnetv2_m-512-aug-epoch09-sgkf1-val_loss0.7077.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
python run.py lr=1e-4 model=unet_smp_2c logger=True project=siim-covid-model-2c-cv fold=2 img_size=512 gpus="cuda:0" epoch=5 w_enc=0.1 w_seg=0.0 losses=cls smp_path="/home/lorenzo/siim-covid/output/efficientnetv2-sgkf-512/tu_tf_efficientnetv2_m-512-aug-epoch09-sgkf2-val_loss0.7330.ckpt" checkpoint_dir="/home/lorenzo/siim-covid/pl_output_2c"
